# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 5
    - nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 1 npm -g install npm
  - IF %nodejs_version% LSS 1 set PATH=%APPDATA%\npm;%PATH%
  - npm install
  # - IF %nodejs_version% EQU 0.8 npm install
  # - IF %nodejs_version% NEQ 0.8 npm install --msvs_version=2013

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - npm ls
  - npm test

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json 
