build: false
skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "Current"

configuration: Release
platform:
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - SET PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm i

test_script:
  - node --version
  - npm --version
  - npm run test

before_deploy:
  - SET ARCHIVE_NAME=%APPVEYOR_REPO_TAG_NAME%-win32-%PLATFORM%.tar.gz
  - npm run prebuild
  - tar -zcvf "%ARCHIVE_NAME%" -C prebuilds .
  - appveyor PushArtifact %ARCHIVE_NAME%

deploy:
  - provider: GitHub
    artifact: $(ARCHIVE_NAME)
    auth_token:
      secure: wfW7RWDvNKnF2haNaW7GVa/xi7Ot4yy6puIAsN2mjmHJQtQpx3XvH+6lf2Tr8Xr9
    draft: false
    on:
      appveyor_repo_tag: true
      nodejs_version: "Current"
