sudo: false
env:
  - CXX=g++-4.8
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
before_install:
  - $CXX --version

# http://docs.travis-ci.com/user/migrating-from-legacy
# sudo: false
